minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
java_version=17

loader=forge
forge_version=1.20.1-47.4.23
platform_version_range=[47,)
loader_version_range=[0,)

parchment_minecraft_version=1.20.1
parchment_mappings_version=2023.09.03

flywheel_vendored=false
flywheel_artifact=flywheel-forge-1.20.1
flywheel_version=1.0.6-281
flywheel_version_range=[1.0,2.0)

flywheel_vendored_version=

lwjgl_version=3.3.1
ktx_supported=false

iris_supported=false
sodium_version=
iris_version=
irisflw_version=

run_dir=run-1.20.1
run_data_dir=run-data-1.20.1
gametest_namespaces_property=forge.enabledGameTestNamespaces

direct_supported=true

harness_supported=true
bench_supported=false
version_buildable=true
